# URL of the API reference table of contents
# check out if you have the latest version url here:
# http://cloud.mindtouch.us/CloudStack_Documentation/API_Reference%3A_CloudStack
api_ref_toc_url: http://download.cloud.com/releases/3.0.0/api_3.0.0/TOC_Root_Admin.html

# Language for generated code (supported: php, python)
language: php

# Generated class name
class_name: CloudStackClient

# Use camel case variable or not
use_camel_case: true

# Camel case values
camel_case:
    accept: accept
    account: account
    accountdetails: accountDetails
    accountid: accountId
    accounts: accounts
    accounttype: accountType
    acltype: aclType
    activeonly: activeOnly
    aggregatename: aggregateName
    algorithm: algorithm
    allocatedonly: allocatedOnly
    allocationstate: allocationState
    applied: applied
    associatednetworkid: associatedNetworkId
    availability: availability
    available: available
    binddn: bindDn
    bindpass: bindPass
    bits: bits
    bootable: bootable
    broadcastdomainrange: broadcastDomainRange
    category: category
    certificate: certificate
    changecidr: changeCidr
    checksum: checksum
    cidrlist: cidrList
    cleanup: cleanup
    clusterid: clusterId
    clustername: clusterName
    clustertype: clusterType
    component: component
    conservemode: conserveMode
    cpunumber: cpuNumber
    cpuspeed: cpuSpeed
    customized: customized
    description: description
    destinationphysicalnetworkid: destinationPhysicalNetworkId
    destzoneid: destzoneId
    details: details
    deviceid: deviceId
    dhcpprovider: dhcpProvider
    disksize: diskSize
    diskofferingid: diskOfferingId
    displayname: displayName
    displaytext: displayText
    dns1: dns1
    dns2: dns2
    dnssearchorder: dnsSearchOrder
    domain: domain
    domainid: domainId
    domainId: domainId
    domainsuffix: domainSuffix
    duration: duration
    email: email
    enabled: enabled
    enddate: endDate
    endip: endIp
    endport: endPort
    entrytime: entryTime
    fetchlatest: fetchLatest
    fingerprint: fingerprint
    firstname: firstName
    forced: forced
    forcedestroylocalstorage: forceDestroyLocalStorage
    forloadbalancing: forLoadBalancing
    format: format
    forvirtualnetwork: forVirtualNetwork
    fwdevicecapacity: fwDeviceCapacity
    fwdeviceid: fwDeviceId
    gateway: gateway
    group: group
    groupid: groupId
    guestcidraddress: guestCidrAddress
    guestiptype: guestIpType
    haenable: haEnable
    hostid: hostId
    hostname: hostName
    hosttags: hostTags
    hypervisor: hypervisor
    icmpcode: icmpCode
    icmptype: icmpType
    id: id
    ids: ids
    inline: inline
    instance: instance
    intervaltype: intervalType
    internaldns1: internalDns1
    internaldns2: internalDns2
    ipaddress: ipAddress
    ipaddressid: ipAddressId
    iprange: ipRange
    iptonetworklist: ipToNetworkList
    iqn: iqn
    iscleanuprequired: isCleanUpRequired
    isdefault: isDefault
    isextractable: isExtractable
    isfeatured: isFeatured
    isofilter: isoFilter
    isolationmethods: isolationMethods
    ispublic: isPublic
    isready: isReady
    isrecursive: isRecursive
    isshared: isShared
    issourcenat: isSourceNat
    issystem: isSystem
    istagged: isTagged
    isstaticnat: isStaticNat
    jobid: jobId
    key: key
    keyboard: keyboard
    keypair: keyPair
    keyword: keyword
    kvmnetworklabel: kvmNetworkLabel
    lastname: lastName
    lbdevicecapacity: lbDeviceCapacity
    lbdevicededicated: lbDeviceDedicated
    lbdeviceid: lbDeviceId
    lbruleid: lbRuleId
    level: level
    limitcpuuse: limitCpuUse
    listall: listAll
    lock: lock
    managedstate: managedState
    max: max
    maxguestslimit: maxGuestsLimit
    maxsnaps: maxSnaps
    memory: memory
    methodname: methodName
    mode: mode
    name: name
    netmask: netmask
    networkdeviceparameterlist: networkDeviceParameterList
    networkdevicetype: networkDeviceType
    networkdomain: networkDomain
    networkid: networkId
    networkids: networkIds
    networkofferingid: networkOfferingId
    networkspeed: networkSpeed
    networkrate: networkRate
    networktype: networkType
    newname: newName
    nspid: nspId
    offerha: offerHa
    op: op
    openfirewall: openFirewall
    oscategoryid: osCategoryId
    ostypeid: osTypeId
    page: page
    pagesize: pageSize
    param: param
    parentdomainid: parentDomainId
    password: password
    passwordenabled: passwordEnabled
    path: path
    physicalnetworkid: physicalNetworkId
    podid: podId
    policyid: policyId
    poolname: poolName
    port: port
    privateendport: privateEndPort
    privatekey: privateKey
    privateport: privatePort
    projectid: projectId
    projectids: projectIds
    protocol: protocol
    provider: provider
    publicendport: publicEndPort
    publicipid: publicIpId
    publickey: publicKey
    publicport: publicPort
    queryfilter: queryFilter
    requireshvm: requireShvm
    resourcestate: resourceState
    resourcetype: resourceType
    restartrequired: restartRequired
    role: role
    schedule: schedule
    searchbase: searchBase
    securitygroupenabled: securityGroupEnabled
    securitygroupid: securityGroupId
    securitygroupids: securityGroupIds
    securitygroupname: securityGroupName
    securitygroupnames: securityGroupNames
    service: service
    servicecapabilitylist: serviceCapabilityList
    servicelist: serviceList
    serviceofferingid: serviceOfferingId
    serviceproviderlist: serviceProviderList
    showcapacities: showCapacities
    size: size
    snapshotid: snapshotId
    snapshotpolicy: snapshotPolicy
    snapshotreservation: snapshotReservation
    snapshottype: snapshotType
    sortby: sortBy
    sortkey: sortKey
    sourcenatsupported: sourceNatSupported
    sourcezoneid: sourceZoneId
    specifyipranges: specifyIpRanges
    specifyvlan: specifyVlan
    sshkeyenabled: sshKeyEnabled
    ssl: ssl
    startdate: startDate
    startip: startIp
    startport: startPort
    state: state
    storageid: storageId
    storagetype: storageType
    subdomainaccess: subdomainAccess
    supportedservices: supportedServices
    systemvmtype: systemVmType
    tags: tags
    templatefilter: templateFilter
    templateid: templateId
    templatetag: templateTag
    timezone: timezone
    token: token
    traffictype: trafficType
    truststore: trustStore
    truststorepass: trustStorePass
    type: type
    url: url
    userapikey: userApiKey
    userdata: userData
    userid: userId
    username: userName
    usersecretkey: userSecretKey
    usersecuritygrouplist: userSecurityGroupList
    value: value
    virtualmachineid: virtualMachineId
    virtualmachineids: virtualMachineIds
    vlan: vlan
    vlanid: vlanId
    vmwarenetworklabel: vmwareNetworkLabel
    volumeid: volumeId
    volumename: volumeName
    xennetworklabel: xenNetworkLabel
    zoneid: zoneId
